#ifndef _DIO_CONFIGURATION_H
#define _DIO_CONFIGURATION_H

//Initial Direction for all pins:

// Options: DIO_u8_INITIAL_INPUT
//          DIO_u8_INITIAL_OUTPUT


//PORTA:
#define DIO_u8_PA0_DIRECTION        DIO_u8_INITIAL_INPUT
#define DIO_u8_PA1_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PA2_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PA3_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PA4_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PA5_DIRECTION		DIO_u8_INITIAL_INPUT	
#define DIO_u8_PA6_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PA7_DIRECTION		DIO_u8_INITIAL_INPUT

//PORTB
#define DIO_u8_PB0_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB1_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB2_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB3_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB4_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB5_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB6_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PB7_DIRECTION		DIO_u8_INITIAL_OUTPUT


//PORTC 
#define DIO_u8_PC0_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PC1_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PC2_DIRECTION		DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PC3_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PC4_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PC5_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PC6_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PC7_DIRECTION		DIO_u8_INITIAL_INPUT


//PORTD
#define DIO_u8_PD0_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PD1_DIRECTION		DIO_u8_INITIAL_INPUT	
#define DIO_u8_PD2_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PD3_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PD4_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PD5_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PD6_DIRECTION		DIO_u8_INITIAL_INPUT
#define DIO_u8_PD7_DIRECTION		DIO_u8_INITIAL_INPUT





//Initial Values for all pins:
// Options: DIO_u8_INITIAL_OUTPUT_LOW
//          DIO_u8_INITIAL_OUTPUT_HIGH
//          DIO_u8_INITIAL_INPUT_FLOATING
//          DIO_u8_INITIAL_INPUT_PULLUP


//PORTA:
#define DIO_u8_PA0_Value        DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA1_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA2_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA3_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA4_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA5_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA6_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PA7_Value		DIO_u8_INITIAL_INPUT_FLOATING

//PORTB
#define DIO_u8_PB0_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB1_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB2_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB3_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB4_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB5_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB6_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PB7_Value		DIO_u8_INITIAL_INPUT_FLOATING


//PORTC 
#define DIO_u8_PC0_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC1_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC2_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC3_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC4_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC5_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC6_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PC7_Value		DIO_u8_INITIAL_INPUT_FLOATING


//PORTD
#define DIO_u8_PD0_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD1_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD2_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD3_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD4_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD5_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD6_Value		DIO_u8_INITIAL_INPUT_FLOATING
#define DIO_u8_PD7_Value		DIO_u8_INITIAL_INPUT_FLOATING








#endif 
